from openfda.tests.api_test_helpers import *


def assert_enough_results(query, count):
    meta, results = fetch(query)
    assert (
        meta["results"]["total"] > count
    ), "Query %s returned fewer results than expected: %d vs %d" % (
        query,
        count,
        meta["results"]["total"],
    )


def test_counts_with_patient_problems():
    assert_enough_results(
        "/device/event.json?search=_exists_:patient.patient_problems", 10361000
    )


def test_counts_with_product_problems():
    assert_enough_results(
        "/device/event.json?search=_exists_:product_problems", 10375000
    )


def test_exact_count():
    assert_count_top(
        "/device/event.json?count=type_of_report.exact",
        ["Initial submission", "Followup"],
    )


def test_exact_product_problems_count():
    assert_count_top(
        query="/device/event.json?count=product_problems.exact&limit=1000",
        N=1000,
        expected_terms=[
            "Adverse Event Without Identified Device or Use Problem",
            "Device Displays Incorrect Message",
            "Break",
            "Device Operates Differently Than Expected",
            "Insufficient Information",
            "Failure to Osseointegrate",
            "Wireless Communication Problem",
            "Appropriate Term/Code Not Available",
            "Loss of Osseointegration",
            "No Device Output",
            "Patient Device Interaction Problem",
            "Incorrect, Inadequate or Imprecise Resultor Readings",
            "Fluid Leak",
            "Device Dislodged or Dislocated",
            "Over-Sensing",
            "No Display/Image",
            "Mechanical Problem",
            "Imprecision",
            "Leak/Splash",
            "High impedance",
            "Fracture",
            "Crack",
            "Battery Problem",
            "Device Inoperable",
            "Failure to Power Up",
            "Osseointegration Problem",
            "Device Alarm System",
            "Use of Device Problem",
            "Material Rupture",
            "Pumping Stopped",
            "Detachment Of Device Component",
            "No Apparent Adverse Event",
            "Premature Discharge of Battery",
            "Power Problem",
            "Detachment of Device or Device Component",
            "Improper or Incorrect Procedure or Method",
            "Communication or Transmission Problem",
            "Incorrect Or Inadequate Test Results",
            "Migration or Expulsion of Device",
            "Connection Problem",
            "Defective Device",
            "Charging Problem",
            "Obstruction of Flow",
            "High Test Results",
            "Malposition of Device",
            "High Capture Threshold",
            "Inappropriate/Inadequate Shock/Stimulation",
            "Nonstandard Device",
            "Failure to Capture",
            "Device Sensing Problem",
            "Material Integrity Problem",
            "Bent",
            "Difficult to Remove",
            "Device Slipped",
            "Incorrect Measurement",
            "Device Difficult to Program or Calibrate",
            "Signal Artifact/Noise",
            "Display or Visual Feedback Problem",
            "Patient-Device Incompatibility",
            "Device Contamination with Chemical or Other Material",
            "Material Deformation",
            "Electrical /Electronic Property Problem",
            "Overheating of Device",
            "Material Separation",
            "Loss of Power",
            "Naturally Worn",
            "Occlusion Within Device",
            "Under-Sensing",
            "Material Twisted/Bent",
            "Sticking",
            "Computer Software Problem",
            "Component Missing",
            "Loose or Intermittent Connection",
            "Unintended Movement",
            "Material Erosion",
            "Failure to Deliver",
            "Failure to Fire",
            "Invalid Sensing",
            "Failure to Sense",
            "Noise, Audible",
            "Low impedance",
            "Poor Quality Image",
            "Loss of or Failure to Bond",
            "Low Test Results",
            "Corroded",
            "Impedance Problem",
            "Positioning Problem",
            "Structural Problem",
            "Air Leak",
            "Failure to Advance",
            "Premature End-of-Life Indicator",
            "Overfill",
            "Moisture or Humidity Problem",
            "No Audible Alarm",
            "Pacing Problem",
            "Migration",
            "Physical Resistance/Sticking",
            "Activation, Positioning or SeparationProblem",
            "Inappropriate or Unexpected Reset",
            "Retraction Problem",
            "Mechanical Jam",
            "Filling Problem",
            "Positioning Failure",
            "Insufficient Flow or Under Infusion",
            "Device Stops Intermittently",
            "Output Problem",
            "Circuit Failure",
            "Failure to Form Staple",
            "Difficult to Insert",
            "Failure to Deliver Energy",
            "Temperature Problem",
            "Capturing Problem",
            "Image Display Error/Artifact",
            "Moisture Damage",
            "Disconnection",
            "Failure to Charge",
            "Difficult to Open or Close",
            "Unable to Obtain Readings",
            "Excess Flow or Over-Infusion",
            "Therapeutic or Diagnostic Output Failure",
            "Failure to Prime",
            "Failure of Device to Self-Test",
            "False Alarm",
            "Contamination",
            "Self-Activation or Keying",
            "Computer Operating System Problem",
            "Infusion or Flow Problem",
            "Unstable",
            "Component Falling",
            "Defective Component",
            "Defective Alarm",
            "Inadequacy of Device Shape and/or Size",
            "Failure To Adhere Or Bond",
            "Metal Shedding Debris",
            "Failure to Interrogate",
            "Failure to Read Input Signal",
            "Low Battery",
            "Entrapment of Device",
            "Failure to Cycle",
            "Difficult or Delayed Activation",
            "False Positive Result",
            "Kinked",
            "Application Interface Becomes Non-Functional Or Program Exits Abnormally",
            "Data Problem",
            "Inaccurate Delivery",
            "Visual Prompts will not Clear",
            "Product Quality Problem",
            "Failure to Cut",
            "Material Protrusion/Extrusion",
            "Inflation Problem",
            "Other (for use when an appropriate device code cannot be identified)",
            "Material Fragmentation",
            "Scratched Material",
            "Device-Device Incompatibility",
            "Suction Problem",
            "Human-Device Interface Problem",
            "Unexpected Therapeutic Results",
            "Improper Flow or Infusion",
            "Ambient Noise Problem",
            "Deflation Problem",
            "Protective Measures Problem",
            "Device Markings/Labelling Problem",
            "Fail-Safe Problem",
            "Partial Blockage",
            "Degraded",
            "Unexpected Shutdown",
            "Unintended System Motion",
            "Misfire",
            "Burst Container or Vessel",
            "Mechanics Altered",
            "Unintended Collision",
            "Packaging Problem",
            "Fitting Problem",
            "Display Difficult to Read",
            "Device Operational Issue",
            "Failure to Align",
            "Torn Material",
            "Electromagnetic Interference",
            "No Flow",
            "Thermal Decomposition of Device",
            "Calibration Problem",
            "Failure to Calibrate",
            "Volume Accuracy Problem",
            "Difficult To Position",
            "Dull, Blunt",
            "Peeled/Delaminated",
            "Material Split, Cut or Torn",
            "Hole In Material",
            "False Negative Result",
            "Deformation Due to Compressive Stress",
            "False Reading From Device Non-Compliance",
            "Physical Resistance",
            "High Readings",
            "Device Damaged Prior to Use",
            "Therapy Delivered to Incorrect Body Area",
            "Difficult to Advance",
            "Energy Output Problem",
            "Reset Problem",
            "Pacemaker Found in Back-Up Mode",
            "Material Puncture/Hole",
            "Material Discolored",
            "Premature Activation",
            "Microbial Contamination of Device",
            "Premature Elective Replacement Indicator",
            "Pumping Problem",
            "Intermittent Continuity",
            "Decreased Sensitivity",
            "Date/Time-Related Software Problem",
            "Separation Failure",
            "Biocompatibility",
            "Gas Leak",
            "Application Program Freezes, Becomes Nonfunctional",
            "Material Frayed",
            "Smoking",
            "Device Damaged by Another Device",
            "Device Emits Odor",
            "Defibrillation/Stimulation Problem",
            "Off-Label Use",
            "Difficult or Delayed Positioning",
            "Loss of Data",
            "Misassembled",
            "Pressure Problem",
            "Perivalvular Leak",
            "Priming Problem",
            "Device Issue",
            "Aspiration Issue",
            "Device Appears to Trigger Rejection",
            "Unintended Application Program Shut Down",
            "Output below Specifications",
            "Use of Incorrect Control Settings",
            "Melted",
            "Disassembly",
            "Loosening of Implant Not Related to Bone-Ingrowth",
            "Non Reproducible Results",
            "Erratic or Intermittent Display",
            "Activation Failure",
            "Intermittent Capture",
            "Electromagnetic Compatibility Problem",
            "Vibration",
            "Delivered as Unsterile Product",
            "Contamination /Decontamination Problem",
            "Low Readings",
            "Incomplete Coaptation",
            "Delayed Charge Time",
            "Stretched",
            "Material Disintegration",
            "Device Or Device Fragments Location Unknown",
            "Device Handling Problem",
            "Complete Blockage",
            "Device Reprocessing Problem",
            "Inadequate User Interface",
            "Unstable Capture Threshold",
            "Fire",
            "Calcified",
            "Tear, Rip or Hole in Device Packaging",
            "Unsealed Device Packaging",
            "Sparking",
            "Device Packaging Compromised",
            "Pocket Stimulation",
            "Extrusion",
            "Collapse",
            "Gradient Increase",
            "Short Fill",
            "Manufacturing, Packaging or Shipping Problem",
            "Cut In Material",
            "Electrical Shorting",
            "Improper Device Output",
            "Programming Issue",
            "Expulsion",
            "Unraveled Material",
            "Out-Of-Box Failure",
            "Device Contaminated During Manufacture or Shipping",
            "Device Remains Activated",
            "Inaccurate Flow Rate",
            "Misconnection",
            "Failure to Shut Off",
            "High Sensing Threshold",
            "Split",
            "Complete Loss of Power",
            "Decrease in Pressure",
            "Application Program Problem",
            "Device Fell",
            "Decrease in Suction",
            "Restricted Flow rate",
            "Failure to Infuse",
            "Device Contamination with Body Fluid",
            "Failure To Run On AC/DC",
            "Device Tipped Over",
            "Patient Data Problem",
            "Failure to Recalibrate",
            "Grounding Malfunction",
            "Reflux within Device",
            "Excessive Heating",
            "Firing Problem",
            "Failure to Deliver Shock/Stimulation",
            "Failure To Service",
            "No Audible Prompt/Feedback",
            "Flaked",
            "Failure to Discharge",
            "Device Ingredient or Reagent Problem",
            "Unintended Head Motion",
            "Device Difficult to Setup or Prepare",
            "Optical Problem",
            "Unknown (for use when the device problem is not known)",
            "Low Sensing Threshold",
            "Failure to Convert Rhythm",
            "Energy Output To Patient Tissue Incorrect",
            "Unintended Ejection",
            "Increase in Pressure",
            "Failure to Obtain Sample",
            "Calibration Error",
            "Operating System Becomes Nonfunctional",
            "Material Perforation",
            "Failure to Disconnect",
            "Device Expiration Issue",
            "Intermittent Loss of Power",
            "Environmental Compatibility Problem",
            "Missing Test Results",
            "Activation Problem",
            "Premature Separation",
            "Free or Unrestricted Flow",
            "Electronic Property Issue",
            "Insufficient Heating",
            "Particulates",
            "Intermittent Infusion",
            "Suction Failure",
            "No Pacing",
            "Compatibility Problem",
            "Arcing",
            "Inappropriate Audible Prompt/Feedback",
            "Insufficient Cooling",
            "Coagulation in Device or Device Ingredient",
            "Fail-Safe Did Not Operate",
            "Telemetry Discrepancy",
            "Device Maintenance Issue",
            "Physical Property Issue",
            "Unintended Power Up",
            "Delamination",
            "Component Misassembled",
            "Gas Output Problem",
            "Material Too Rigid or Stiff",
            "Decreased Pump Speed",
            "Backflow",
            "Device Contamination With Biological Material",
            "Low Audible Alarm",
            "Audible Prompt/Feedback Problem",
            "Separation Problem",
            "Incorrect Interpretation of Signal",
            "Needle, separation",
            "Electrical Power Problem",
            "Sensing Intermittently",
            "Component or Accessory Incompatibility",
            "Shelf Life Exceeded",
            "Failure to Auto Stop",
            "Failure to Pump",
            "Contamination of Device Ingredient or Reagent",
            "Failure to Analyze Signal",
            "Material Opacification",
            "Shipping Damage or Problem",
            "Failure to Clean Adequately",
            "No Pressure",
            "Labelling, Instructions for Use or Training Problem",
            "Device Misassembled During Manufacturing /Shipping",
            "Explanted",
            "Chemical Spillage",
            "Intermittent Communication Failure",
            "Chemical Problem",
            "Operating System Version or Upgrade Problem",
            "Tidal Volume Fluctuations",
            "Gel Leak",
            "Misfocusing",
            "Power Conditioning Problem",
            "Folded",
            "Charred",
            "Application Program Version or Upgrade Problem",
            "Alarm Not Visible",
            "Device Disinfection Or Sterilization Issue",
            "Failure to Run on Battery",
            "Difficult to Interrogate",
            "Missing Value Reason",
            "Failure to Back-Up",
            "Installation-Related Problem",
            "Environmental Particulates",
            "Inability to Irrigate",
            "Sharp Edges",
            "Tip breakage",
            "Battery Problem: High Impedance",
            "Malfunction",
            "Difficult to Fold, Unfold or Collapse",
            "Failure to Select Signal",
            "Reaction",
            "Incorrect Software Programming Calculations",
            "Incorrect Device Or Component Shipped",
            "Shielding Failure",
            "Material Distortion",
            "Inaudible or Unclear Audible Prompt/Feedback",
            "Dent in Material",
            "Output above Specifications",
            "Intermittent Energy Output",
            "Loss of Threshold",
            "Component Incompatible",
            "Image Resolution Poor",
            "Delivery System Failure",
            "Accessory Incompatible",
            "Incomplete or Missing Packaging",
            "Implant, removal of",
            "Improper Chemical Reaction",
            "Inadequate or Insufficient Training",
            "Illegible Information",
            "Incomplete or Inadequate Connection",
            "Difficult to Open or Remove Packaging Material",
            "Application Program Problem: Dose Calculation Error",
            "Missing Information",
            "Failure to Reset",
            "Maintenance Does Not Comply To Manufacturers Recommendations",
            "Improper Alarm",
            "Interrogation Problem",
            "Inadequate Instructions for Healthcare Professional",
            "Difficult to Flush",
            "Device Abrasion From Instrument Or Another Object",
            "Inability to Auto-Fill",
            "Expiration Date Error",
            "Inadequate Instructions for Non-Healthcare Professional",
            "Failure to Unfold or Unwrap",
            "Looping",
            "Problem with Software Installation",
            "Blocked Connection",
            "Residue After Decontamination",
            "Aborted Charge",
            "Difficult or Delayed Separation",
            "Failure to Zero",
            "Flare or Flash",
            "Filtration Problem",
            "Pacing Inadequately",
            "Inadequate Ultra Filtration",
            "Component(s), broken",
            "Misassembly by Users",
            "Device remains implanted",
            "Failure to Transmit Record",
            "Issue With Displayed Error Message",
            "Loose",
            "Failure to Eject",
            "Human Factors Issue",
            "Data Back-Up Problem",
            "Flushing Problem",
            "Inaccurate Synchronization",
            "Unintended Electrical Shock",
            "Unintended Arm Motion",
            "Electro-Static Discharge",
            "Failure to Conduct",
            "Pacing Intermittently",
            "Inaccurate Information",
            "Knotted",
            "Application Program Problem: Medication Error",
            "Failure to Fold",
            "Device, or device fragments remain in patient",
            "Fail-Safe Design Failure",
            "Solder Joint Fracture",
            "Ejection Problem",
            "Ventilation Problem in Device Environment",
            "Air/Gas in Device",
            "Image Orientation Incorrect",
            "Inadequate Lighting",
            "Tears, rips, holes in device, device material",
            "Problem with Sterilization",
            "Radiation Overexposure",
            "Optical Distortion",
            "Application Program Problem: Parameter Calculation Error",
            "Material Invagination",
            "Pitted",
            "Coiled",
            "Inadequate Filtration Process",
            "Lens, vaulting",
            "Increase in Suction",
            "Key or Button Unresponsive/not Working",
            "Alarm, audible",
            "Radiofrequency Interference (RFI)",
            "Arcing of Electrodes",
            "Sediment, Precipitate Or Deposit In Device Or Device Ingredient",
            "Material Too Soft/Flexible",
            "Inaccurate Dispensing",
            "Increased Sensitivity",
            "Battery Impedance Issue",
            "False Device Output",
            "Precipitate in Device or Device Ingredient",
            "Explosion",
            "Material Torqued",
            "Pacing Asynchronously",
            "Excessive Cooling",
            "Mushroomed",
            "Uncoiled",
            "Overcorrection",
            "Decoupling",
            "Lens (IOL), torn, split, cracked",
            "Device Difficult to Maintain",
            "Increased Pump Speed",
            "Fumes or Vapors",
            "Inadequate Storage",
            "Fungus in Device Environment",
            "Measurement System Incompatibility",
            "Implant extrusion",
            "Medical Gas Supply Problem",
            "Battery Problem: Low Impedance",
            "Inappropriate Waveform",
            "Balloon leak(s)",
            "Optical Discoloration",
            "Intermittent Shock/Stimulation",
            "Wrinkled",
            "Continuous Firing",
            "Fogging",
            "Ambient Temperature Problem",
            "Balloon rupture",
            "No Fail-Safe Mechanism",
            "Image Reversal",
            "Normal",
            "Disposable",
            "Delayed Alarm",
            "Lack of Maintenance Documentation or Guidelines",
            "Radio Signal Problem",
            "Implant Mobility NOS (Not otherwise specified)",
            "Program, failure to",
            "Optical Obstruction",
            "Device Unsafe to Use in Environment",
            "Biofilm coating in Device",
            "Wire(s), breakage of",
            "Inadequate Service",
            "Unclear Information",
            "Misassembled During Installation",
            "Program or Algorithm Execution Problem",
            "Failure to Deflate",
            "Failure to Disinfect",
            "Application Network Problem",
            "Dome collapse",
            "Optical Decentration",
            "Unauthorized Access to Computer System",
            "Absorption",
            "Clumping in Device or Device Ingredient",
            "Electrical Overstress",
            "Radiation Output Failure",
            "Computer System Security Problem",
            "No Visual Prompts/Feedback",
            "Valve(s), failure of",
            "Misassembly During Maintenance/Repair",
            "Dislocated",
            "Light Interference",
            "No Tactile Prompts/Feedback",
            "Balloon burst",
            "Changes In Ambient Temperature In Device Environment",
            "Plunge",
            "Program or Algorithm Execution Failure",
            "Device Rinsing Issue",
            "Hot Oil Leak",
            "Radiation Leak",
            "Unintended Deflation",
            "Motor failure",
            "Tactile Prompts/Feedback",
            "Battery charger, defective",
            "Application Program Problem: Power Calculation Error",
            "Biological Environmental Factor",
            "Component(s), worn",
            "Foreign material",
            "Radiation Output Problem",
            "Energy Spectrum Incorrect",
            "Deflation, cause unknown",
            "Unexpected/Unintended Radiation Output",
            "Measurements, inaccurate",
            "Premature Indicator Activation",
            "Radiation Underexposure",
            "Failure to Convert to Back-Up",
            "Locking mechanism failure",
            "Failure To Unwrap",
            "Haptic(s), broken",
            "High pH",
            "Hose line occlusion",
            "Reservoir",
            "Cross Reactivity",
            "Disengaged",
            "Arcing at Paddles",
            "Erratic Results",
            "Unable to confirm conditions of use",
            "Clips, scissored",
            "Alarm, intermittent",
            "Dissection",
            "Device, removal of (non-implant)",
            "Inappropriate Tactile Prompt/Feedback",
            "Facilities Issue",
            "Incorrect Error Code",
            "Lens Damaged in Delivery System",
            "Seal, defective",
            "Application Security Problem",
            "Dislodged",
            "Safety interlock(s) inadequate",
            "Mislabeled",
            "Noise",
            "System fails to activate",
            "Tube(s), splitting of",
            "Overdelivery",
            "Inadequate Lubrication",
            "Unintended Magnet Quench",
            "Problem with Removal of Enzymatic Cleaner",
            "Sharp/jagged/rough/etched/scratched",
            "Needle, unsheathed",
            "Pressure, insufficient",
            "Compatibility",
            "Device Contaminated at the User Facility",
            "Performance",
            "Connection error",
            "Emergency Power Failure",
            "Implant breakage or physical damage",
            "Membrane leak(s)",
            "Pressure sensor failure",
            "Bolus mechanism failure",
            "Interference",
            "Mineralization",
            "Rupture, cause unknown",
            "Escape",
            "Fuse, blown",
            "Pre Or Post-Pumping Problem",
            "Source, detachment from",
            "Thickening of Material",
            "Capacitative Coupling",
            "Unexpected Color",
            "Cardiac enzyme evaluation, erroneous",
            "Delayed Program or Algorithm Execution",
            "Design/structure problem",
            "Haptic(s), bent",
            "Tube(s), buckling of",
            "Incomplete or Inadequate Priming",
            "Internal fixation, revision of",
            "Lens Stuck in Delivery System",
            "Undercorrection",
            "Replace",
            "Sterility",
            "Blank screen",
            "Close, difficult to",
            "Component(s), overheating of",
            "Deterioration of prosthesis",
            "Displacement",
            "Electrode(s), fracture of",
            "Filter break(s)",
            "Lead(s), fracture of",
            "Misplacement",
            "Poor gas exchange",
            "Alarm, no lead",
            "Spring loading mechanism problem",
            "Unintended Compatibility",
            "Alarm, failure of warning",
            "Cautery",
            "Electro-magnetic interference (EMI), compatibility/incompatibility",
            "Filter",
            "Filter leak(s)",
            "Haptic Damaged in Delivery System",
            "Intended use for traditional use",
            "Intraprocedure, fire or flash during",
            "Lens, disc",
            "Lens, repositioning of",
            "Occlusion, incorrect",
        ],
    )


def test_exact_patient_problems_count():
    assert_count_top(
        query="/device/event.json?count=patient.patient_problems.exact&limit=1000",
        N=1000,
        expected_terms=[
            "No Known Impact Or Consequence To Patient",
            "No Consequences Or Impact To Patient",
            "No Clinical Signs, Symptoms or Conditions",
            "No Patient Involvement",
            "Pain",
            "Failure of Implant",
            "Hyperglycemia",
            "No Code Available",
            "Unspecified Infection",
            "No Information",
            "Tissue Damage",
            "Injury",
            "Hypoglycemia",
            "Death",
            "Insufficient Information",
            "Inadequate Pain Relief",
            "Discomfort",
            "Hemorrhage/Bleeding",
            "Inflammation",
            "Erosion",
            "Peritonitis",
            "Fibrosis",
            "Therapeutic Effects, Unexpected",
            "Therapeutic Response, Decreased",
            "Swelling",
            "Complaint, Ill-Defined",
            "Diabetic Ketoacidosis",
            "Foreign Body In Patient",
            "Capsular Contracture",
            "Surgical procedure",
            "Blood Loss",
            "Device Embedded In Tissue or Plaque",
            "Abdominal Pain",
            "Disability",
            "Foreign Body Reaction",
            "Shock from Patient Lead(s)",
            "Fall",
            "Not Applicable",
            "Nausea",
            "Inadequate Osseointegration",
            "Vomiting",
            "Bone Fracture(s)",
            "Reaction",
            "Numbness",
            "Headache",
            "Osteolysis",
            "Burning Sensation",
            "Dizziness",
            "Bacterial Infection",
            "Joint Dislocation",
            "Incontinence",
            "Ambulation Difficulties",
            "Adhesion(s)",
            "Fatigue",
            "Hernia",
            "Other (for use when an appropriate patient code cannot be identified)",
            "Host-Tissue Reaction",
            "Hypersensitivity/Allergic reaction",
            "Skin Irritation",
            "Hematoma",
            "Appropriate Clinical Signs, Symptoms, Conditions Term / Code Not Available",
            "Cardiac Arrest",
            "Electric Shock",
            "Sepsis",
            "Myocardial Infarction",
            "Thrombosis",
            "Dyspnea",
            "Loss of consciousness",
            "Abscess",
            "Test Result",
            "Fistula",
            "Undesired Nerve Stimulation",
            "Low Blood Pressure/ Hypotension",
            "Perforation",
            "Loss of Range of Motion",
            "Post Operative Wound Infection",
            "Thrombus",
            "Scar Tissue",
            "Blurred Vision",
            "Chest Pain",
            "Syncope",
            "Erythema",
            "Limited Mobility Of The Implanted Joint",
            "Stroke/CVA",
            "Occlusion",
            "Rash",
            "Toxicity",
            "Perforation of Vessels",
            "Seizures",
            "Weakness",
            "Shaking/Tremors",
            "Wound Dehiscence",
            "Cardiac Perforation",
            "Anxiety",
            "Fever",
            "Non-union Bone Fracture",
            "Impaired Healing",
            "Seroma",
            "Urinary Tract Infection",
            "Swelling/ Edema",
            "Patient Problem/Medical Problem",
            "Itching Sensation",
            "Pericardial Effusion",
            "Heavier Menses",
            "Stenosis",
            "Edema",
            "Sweating",
            "Weight Changes",
            "Device Overstimulation of Tissue",
            "Neurological Deficit/Dysfunction",
            "Cardiac Tamponade",
            "Muscle Stimulation",
            "Visual Impairment",
            "Burn(s)",
            "Urinary Frequency",
            "Arrhythmia",
            "Pocket Erosion",
            "Deformity/ Disfigurement",
            "Aortic Valve Stenosis",
            "Necrosis",
            "Emotional Changes",
            "Obstruction/Occlusion",
            "Overdose",
            "Bradycardia",
            "Urinary Retention",
            "Muscular Rigidity",
            "Uterine Perforation",
            "Irritation",
            "Intimal Dissection",
            "Vascular Dissection",
            "Confusion/ Disorientation",
            "Depression",
            "Aortic Regurgitation",
            "Internal Organ Perforation",
            "Aneurysm",
            "Bleeding",
            "Fluid Discharge",
            "Nerve Damage",
            "Unspecified Tissue Injury",
            "Purulent Discharge",
            "Endocarditis",
            "Rupture",
            "Reocclusion",
            "Scarring",
            "Osteopenia/ Osteoporosis",
            "Malaise",
            "Atrial Fibrillation",
            "Menstrual Irregularities",
            "Muscle Spasm(s)",
            "Hemolysis",
            "Laceration(s)",
            "Visual Disturbances",
            "Hair Loss",
            "Polydipsia",
            "Mitral Regurgitation",
            "Increased Sensitivity",
            "Hearing Impairment",
            "Tingling",
            "Sleep Dysfunction",
            "Ventricular Tachycardia",
            "Cyst(s)",
            "Complete Heart Block",
            "Bruise/Contusion",
            "Staphylococcus Aureus",
            "Arthralgia",
            "Cognitive Changes",
            "Underdose",
            "Angina",
            "Twiddlers Syndrome",
            "Cramp(s)",
            "Ventricular Fibrillation",
            "Cerebrospinal Fluid Leakage",
            "Keratitis",
            "Abdominal Distention",
            "Heart Failure",
            "High Blood Pressure/ Hypertension",
            "Pulmonary Embolism",
            "Diarrhea",
            "Tachycardia",
            "Renal Failure",
            "Failure to Anastomose",
            "Burn, Thermal",
            "Joint Swelling",
            "Ischemia",
            "Discharge",
            "Non specific EKG/ECG Changes",
            "Joint Disorder",
            "Needle Stick/Puncture",
            "Vessel Or Plaque, Device Embedded In",
            "Granuloma",
            "Synovitis",
            "Dehydration",
            "Capsular Bag Tear",
            "Muscle Weakness",
            "Pneumothorax",
            "Paralysis",
            "Skin Inflammation/ Irritation",
            "Micturition Urgency",
            "Low Oxygen Saturation",
            "Infarction, Cerebral",
            "Palpitations",
            "Ossification",
            "Calcium Deposits/Calcification",
            "Halo",
            "Respiratory Distress",
            "Partial thickness (Second Degree) Burn",
            "Respiratory Failure",
            "Extubate",
            "Pneumonia",
            "Memory Loss/Impairment",
            "Embolism",
            "Anemia",
            "Mitral Valve Stenosis",
            "Lethargy",
            "Distress",
            "Surgical procedure, additional",
            "Abdominal Cramps",
            "Aortic Insufficiency",
            "Intraocular Pressure Increased",
            "Skin Discoloration",
            "Thrombosis/Thrombus",
            "Shock",
            "Dysphagia/ Odynophagia",
            "Abnormal Vaginal Discharge",
            "Hemorrhage, Cerebral",
            "Deafness",
            "Neuropathy",
            "Hematuria",
            "Constipation",
            "Chills",
            "Fainting",
            "Cellulitis",
            "Local Reaction",
            "Coma",
            "Joint Laxity",
            "Vascular System (Circulation), Impaired",
            "Chemical Exposure",
            "Neck Pain",
            "Dry Eye(s)",
            "Cardiopulmonary Arrest",
            "Alteration In Body Temperature",
            "Dysphasia",
            "Head Injury",
            "Vitrectomy",
            "Abrasion",
            "Tissue Breakdown",
            "Radiation Exposure, Unintended",
            "Fungal Infection",
            "Red Eye(s)",
            "Pseudoaneurysm",
            "Prolapse",
            "Sinus Perforation",
            "Eye Injury",
            "Autoimmune Reaction",
            "Intracranial Hemorrhage",
            "Foreign body, removal of",
            "Skin Inflammation",
            "Loss of Vision",
            "Congestive Heart Failure",
            "Skin Erosion",
            "Surgical procedure, repeated",
            "Pelvic Inflammatory Disease",
            "Cancer",
            "Cardiac Enzyme Elevation",
            "Pregnancy",
            "Arthritis",
            "Pleural Effusion",
            "Hip Fracture",
            "Transient Ischemic Attack",
            "Irritability",
            "Corneal Ulcer",
            "Postoperative refraction, unexpected",
            "Sedation",
            "Regurgitation",
            "Pressure Sores",
            "Dysuria",
            "Heart Failure/Congestive Heart Failure",
            "Bowel Perforation",
            "Ulcer",
            "Extrusion",
            "Cardiogenic Shock",
            "Multiple Organ Failure",
            "Therapy/non-surgical treatment, additional",
            "Implant Pain",
            "Unknown (for use when the patient''s condition is not known)",
            "Air Embolism",
            "Unspecified Respiratory Problem",
            "Iatrogenic Source",
            "Treatment with medication(s)",
            "Thromboembolism",
            "Autoimmune Disorder",
            "Corneal Edema",
            "Hearing Loss",
            "Exposure to Body Fluids",
            "Hypoxia",
            "Extravasation",
            "Swollen Lymph Nodes",
            "Skin Infection",
            "Twitching",
            "Paresis",
            "Syncope/Fainting",
            "Diaphoresis",
            "Foreign Body Sensation in Eye",
            "Urticaria",
            "Metal Related Pathology",
            "Septic Shock",
            "Skin Tears",
            "Hemorrhage, Subarachnoid",
            "Tinnitus",
            "Vertigo",
            "Full thickness (Third Degree) Burn",
            "Great Vessel Perforation",
            "ST Segment Elevation",
            "Endophthalmitis",
            "Headache, Lumbar Puncture",
            "Lymphoma",
            "Hot Flashes/Flushes",
            "Aortic Dissection",
            "Exit Block",
            "Claudication",
            "Vasoconstriction",
            "Coagulation Disorder",
            "Hydrocephalus",
            "Sudden Cardiac Death",
            "Eye Burn",
            "Spinal Column Injury",
            "Superficial (First Degree) Burn",
            "Excessive Tear Production",
            "Aspiration/Inhalation",
            "Chest Tightness/Pressure",
            "Pulmonary Valve Stenosis",
            "Apnea",
            "Wrinkling",
            "Embolus",
            "Corneal Pannus",
            "Brain Injury",
            "Intermenstrual Bleeding",
            "Meningitis",
            "Breast Mass",
            "Heart Block",
            "Corneal Abrasion",
            "Pulmonary Edema",
            "Hypervolemia",
            "Atrial Perforation",
            "Thyroid Problems",
            "Convulsion/Seizure",
            "Collapse",
            "Tooth Fracture",
            "Ascites",
            "Tricuspid Regurgitation",
            "Flatus",
            "Myalgia",
            "No Patient involvement",
            "Anaplastic Large Cell Lymphoma",
            "Genital Bleeding",
            "Aortic Valve Insufficiency/ Regurgitation",
            "Urinary Incontinence",
            "Ectopic Pregnancy",
            "Right Ventricular Failure",
            "Corneal Clouding/Hazing",
            "Sensitivity of Teeth",
            "Asthma",
            "Choking",
            "Hypoesthesia",
            "Atrial Flutter",
            "Pyrosis/Heartburn",
            "Insufficiency, Valvular",
            "Infiltration into Tissue",
            "Loss Of Pulse",
            "Gastrointestinal Hemorrhage",
            "Physical Entrapment",
            "Intraocular Pressure, Delayed, Uncontrolled",
            "Cardiomyopathy",
            "Ulceration",
            "Hospitalization required",
            "Respiratory Tract Infection",
            "Conjunctivitis",
            "Liver Damage/Dysfunction",
            "Asystole",
            "Misdiagnosis",
            "Corneal Infiltrates",
            "Pulmonary Regurgitation",
            "Menorrhagia",
            "Dyskinesia",
            "Encephalopathy",
            "Organ Dehiscence",
            "Cataract",
            "Caustic/Chemical Burns",
            "Mitral Valve Insufficiency/ Regurgitation",
            "Sore Throat",
            "Miscarriage",
            "Damage to Ligament(s)",
            "Hyperplasia",
            "Nonresorbable materials, unretrieved in body",
            "Physical Asymmetry",
            "Electrolyte Imbalance",
            "Neck Stiffness",
            "Hemoptysis",
            "Unintended Extubation",
            "Awareness during Anaesthesia",
            "Hemothorax",
            "Hemostasis",
            "Ecchymosis",
            "Spinal Cord Injury",
            "Atrial Tachycardia",
            "Regurgitation, Valvular",
            "Reaction, Injection Site",
            "Anaphylactic Shock",
            "Airway Obstruction",
            "Peeling",
            "Missed Dose",
            "Fracture, Arm",
            "Contusion",
            "Paraplegia",
            "Uveitis",
            "Fallopian Tube Perforation",
            "Missing Value Reason",
            "Convulsion, Clonic",
            "Viral Infection",
            "Cramp(s) /Muscle Spasm(s)",
            "Low Cardiac Output",
            "Pallor",
            "Hyphema",
            "Iritis",
            "Exsanguination",
            "Limb Fracture",
            "Valvular Insufficiency/ Regurgitation",
            "Facial Nerve Paralysis",
            "Cataract, Induced",
            "Ptosis",
            "Vitreous Floaters",
            "Blister",
            "Swollen Lymph Nodes/Glands",
            "Cyanosis",
            "Rheumatoid Arthritis",
            "Venipuncture",
            "Hemorrhage, Subdural",
            "Surgery, prolonged",
            "Mitral Insufficiency",
            "Macular Edema",
            "Therapeutic Response, Increased",
            "Colostomy",
            "Tricuspid Valve Stenosis",
            "Embolism/Embolus",
            "Paresthesia",
            "Chronic Obstructive Pulmonary Disease (COPD)",
            "Hypovolemia",
            "Diminished Pulse Pressure",
            "Corneal Scar",
            "Retinal Detachment",
            "Oversedation",
            "Perforation of Esophagus",
            "Necrosis Of Flap Tissue",
            "Bronchitis",
            "Phlebitis",
            "Muscle/Tendon Damage",
            "Decreased Respiratory Rate",
            "Unintended Radiation Exposure",
            "Bowel Burn",
            "Hypopyon",
            "Ventilator Dependent",
            "Ischemia Stroke",
            "Transfusion of blood products",
            "Hyperemia",
            "Cusp Tear",
            "Concussion",
            "Difficulty Chewing",
            "Glaucoma",
            "Extreme Exhaustion",
            "Gastritis",
            "Virus",
            "Dementia",
            "Cough",
            "Debris, Bone Shedding",
            "Malunion of Bone",
            "Restenosis",
            "Hypothermia",
            "Unspecified Nervous System Problem",
            "Lupus",
            "Feeding Problem",
            "Decreased Appetite",
            "Hemorrhagic Stroke",
            "Premature Labor",
            "Hypoventilation",
            "Vitreous Loss",
            "Hypovolemic Shock",
            "Breast Cancer",
            "Seizures, Grand-Mal",
            "Laceration(s) of Esophagus",
            "Atherosclerosis",
            "Vaso-Vagal Response",
            "Radiation Overdose",
            "Allergic reaction",
            "Right Ventricular Dysfunction",
            "Crushing Injury",
            "Nervous System Injury",
            "Sprain",
            "Jaundice",
            "Overcorrection",
            "Pulmonary Insufficiency",
            "Abortion",
            "Nerve Proximity Nos (Not Otherwise Specified)",
            "Nicks, cuts or tears of dura or other tissues by device",
            "Toxic Shock Syndrome",
            "Intraocular Infection",
            "Disc Impingement",
            "Pupillary Block",
            "Intraoperative Pain",
            "Toxic Anterior Segment Syndrome (TASS)",
            "Dyspareunia",
            "Hepatitis",
            "Electro-Mechanical Dissociation",
            "Congenital Defect/Deformity",
            "Lactate Dehydrogenase Increased",
            "Wheal(s)",
            "Renal Disease, End Stage",
            "Eye Pain",
            "Post Traumatic Wound Infection",
            "Increased Respiratory Rate",
            "Hiccups",
            "Ischemic Heart Disease",
            "Valvular Stenosis",
            "Peroneal Nerve Palsy",
            "Diplopia",
            "Subcutaneous Nodule",
            "Laparotomy",
            "Death, Intrauterine Fetal",
            "Gangrene",
            "Drainage",
            "Raynauds Phenomenon",
            "Retinal Tear",
            "Vaginal Mucosa Damage",
            "Anoxia",
            "Irregular Pulse",
            "Abnormal Blood Gases",
            "Foreign Body Embolism",
            "Peripheral Vascular Disease",
            "Pulmonary Emphysema",
            "Zonular Dehiscence",
            "Anaphylactoid",
            "Respiratory Acidosis",
            "Shock, Insulin",
            "Herpes",
            "Acanthameba Keratitis",
            "Surgical procedure, delayed",
            "Impotence",
            "Pulmonary Dysfunction",
            "Adult Respiratory Distress Syndrome",
            "Decreased Sensitivity",
            "Migration",
            "Radiation Burn",
            "Corneal Decompensation",
            "Hemorrhage, Intraventricular",
            "Phototoxicity",
            "Presyncope",
            "Retinal Injury",
            "Fungus",
            "Left Ventricular Failure",
            "Skin Disorders",
            "Left Ventricular Dysfunction",
            "Hemolytic Anemia",
            "Hyperthermia",
            "Hyperventilation",
            "Disseminated Intravascular Coagulation (DIC)",
            "Flashers",
            "Pregnancy with a Contraceptive Device",
            "Sneezing",
            "Suture Abrasion",
            "Renal Impairment",
            "Alteration in Body Temperature",
            "Corneal Perforation",
            "Tricuspid Valve Insufficiency/ Regurgitation",
            "Electrocution",
            "Vasodilatation",
            "Torsades-de-Pointes",
            "Skull Fracture",
            "Arachnoiditis, Spinal",
            "Unequal Limb Length",
            "Immunodeficiency",
            "Epistaxis",
            "Melena",
            "Skin Burning Sensation",
            "Unspecified Vascular Problem",
            "Unspecified Heart Problem",
            "Hyperbilirubinemia",
            "Localized Skin Lesion",
            "Breast Implant Associated Anaplastic Large Cell Lymphoma (BIA ALCL)",
            "Deposits",
            "Sjogren''s Syndrome",
            "Infection, Pyrogenic",
            "Strangulation",
            "Uremia",
            "Lead(s), Burn(s) From",
            "Drug Resistant Bacterial Infection",
            "Bronchospasm",
            "Vitreous Detachment",
            "Painful stimulation",
            "Respiratory Arrest",
            "Bronchopneumonia",
            "Connective Tissue Disease",
            "Blister(s)",
            "Convulsion, Tonic",
            "Hypoesthesia, Foot/Leg",
            "Cardiovascular Insufficiency",
            "Unspecified Kidney or Urinary Problem",
            "Fasciitis",
            "Intervertebral Disc Compression or Protrusion",
            "Vitritis",
            "Breast Discomfort/Pain",
            "Nodule",
            "Unspecified Eye / Vision Problem",
            "Intraocular Pressure Decreased",
            "Tricuspid Insufficiency",
            "Neovascularization",
            "Increased Intra-Peritoneal Volume (IIPV)",
            "Pulmonary Valve Insufficiency/ Regurgitation",
            "Mitral Valve Prolapse",
            "Seizures, Absence",
            "Unspecified Blood or Lymphatic problem",
            "Antibiotics, Reaction To",
            "Asphyxia",
            "Joint Contracture",
            "Reaction to Medicinal Component of Device",
            "Swollen Glands",
            "Cerebral Ventriculomeglia",
            "Stacking Breaths",
            "Ruptured Aneurysm",
            "Vitreous Hemorrhage",
            "HIV, Human Immunodeficiency Virus",
            "Scar Excision",
            "Speech Disorder",
            "Unspecified Mental, Emotional or Behavioural Problem",
            "ST Segment Depression",
            "Clouding, Central Corneal",
            "Liver Laceration(s)",
            "Myocarditis",
            "Teratogenic Effects",
            "Fibromyositis",
            "Nasal Obstruction",
            "Nipple Sensation Changes",
            "Seizures, Focal",
            "Idioventricular Rhythm",
            "Radiation Underdose",
            "Infection, Indirect",
            "Protrusion",
            "Contact Dermatitis",
            "Respiratory Insufficiency",
            "Fetal Distress",
            "Quadriplegia",
            "Suffocation",
            "Neuralgia",
            "Muscular Tics",
            "Leak(s), perivalvular",
            "Left Ventricular Hypertrophy",
            "Subluxation",
            "Unspecified Gastrointestinal Problem",
            "Surgical procedure aborted/stopped",
            "Balance Problems",
            "Bruxism",
            "Eye Infections",
            "Positive antinuclear antibodies (ANA)",
            "Ventricular Flutter",
            "Encephalitis",
            "Hypoesthesia, Arm/Hand",
            "Liver Failure",
            "Osteomyelitis",
            "Retroperitoneal Hemorrhage",
            "Surgical incision, enlargement of",
            "Vertebral Fracture",
            "Seizures, Focal Motor",
            "Pancreatitis",
            "Scleroderma",
            "Solid Tumour",
            "Cancer, Other",
        ],
    )


def test_date():
    assert_total("/device/event.json?search=date_received:20090217", 1)


def test_date_range():
    assert_total("/device/event.json?search=date_received:([20090217+TO+20091231])", 1)


def test_openfda():
    assert_total(
        "/device/event.json?search=device.openfda.regulation_number:892.1650", 1
    )


def test_single_product_problem():
    meta, results = fetch("/device/event.json?search=mdr_report_key:7014707")
    eq_(len(results), 1)
    event = results[0]
    eq_(event["product_problems"], ["Device Displays Incorrect Message"])

    meta, results = fetch(
        '/device/event.json?search=report_number:"0001313525-2021-00110"'
    )
    eq_(len(results), 1)
    event = results[0]
    problems = sorted(event["product_problems"], key=lambda k: k)
    eq_(
        problems,
        [
            "Adverse Event Without Identified Device or Use Problem",
            "Insufficient Information",
        ],
    )

    meta, results = fetch(
        '/device/event.json?search=report_number:"1057985-2021-00146"'
    )
    eq_(len(results), 1)
    event = results[0]
    eq_(
        event["product_problems"],
        ["Adverse Event Without Identified Device or Use Problem"],
    )


def test_multiple_product_problems():
    meta, results = fetch("/device/event.json?search=mdr_report_key:7014702")
    eq_(len(results), 1)

    event = results[0]
    problems = sorted(event["product_problems"], key=lambda k: k)
    eq_(
        problems,
        [
            "Ambient Noise Problem",
            "Fracture",
            "High impedance",
            "Over-Sensing",
            "Pacing Problem",
        ],
    )


def test_multiple_patient_problems():
    meta, results = fetch("/device/event.json?search=mdr_report_key:4102973")
    eq_(len(results), 1)
    event = results[0]
    eq_(len(event["patient"]), 1)
    problems = sorted(event["patient"][0]["patient_problems"], key=lambda k: k)
    eq_(problems, ["Cardiogenic Shock", "Myocardial Infarction", "Thrombosis"])

    meta, results = fetch(
        '/device/event.json?search=report_number:"0001313525-2021-00110"'
    )
    eq_(len(results), 1)
    event = results[0]
    eq_(len(event["patient"]), 1)
    problems = sorted(event["patient"][0]["patient_problems"], key=lambda k: k)
    eq_(problems, ["Corneal Infiltrates", "Corneal Ulcer", "Keratitis"])

    meta, results = fetch(
        '/device/event.json?search=report_number:"1057985-2021-00146"'
    )
    eq_(len(results), 1)
    event = results[0]
    eq_(len(event["patient"]), 1)
    problems = sorted(event["patient"][0]["patient_problems"], key=lambda k: k)
    eq_(
        problems,
        [
            "Blurred Vision",
            "Excessive Tear Production",
            "Eye Pain",
            "Foreign Body Sensation in Eye",
            "Itching Sensation",
            "Red Eye(s)",
        ],
    )


def test_multiple_patients_with_same_problem():
    meta, results = fetch("/device/event.json?search=mdr_report_key:4718251")
    eq_(len(results), 1)

    event = results[0]
    eq_(len(event["patient"]), 4)

    for idx, patient in enumerate(
        sorted(event["patient"], key=lambda k: k["patient_sequence_number"])
    ):
        eq_(patient["patient_sequence_number"], str(idx + 1))
        eq_(
            sorted(patient["patient_problems"], key=lambda k: k),
            ["Injury", "Tissue Damage"],
        )


def test_multiple_patient_problems_without_patient_record_issue_179():
    meta, results = fetch("/device/event.json?search=mdr_report_key:11339476")
    eq_(len(results), 1)
    event = results[0]
    eq_(len(event["patient"]), 1)
    problems = sorted(event["patient"][0]["patient_problems"], key=lambda k: k)
    eq_(problems, ["Blurred Vision", "Visual Disturbances"])

    meta, results = fetch("/device/event.json?search=mdr_report_key:11131671")
    eq_(len(results), 1)
    event = results[0]
    eq_(len(event["patient"]), 1)
    problems = sorted(event["patient"][0]["patient_problems"], key=lambda k: k)
    eq_(problems, ["Visual Disturbances"])


def test_foitext_present():
    meta, results = fetch("/device/event.json?search=mdr_report_key:10131013")
    eq_(len(results), 1)

    event = results[0]
    mdrtext = sorted(event["mdr_text"], key=lambda k: k["mdr_text_key"])
    eq_(len(mdrtext), 2)
    eq_(
        mdrtext[0]["text"],
        "INVESTIGATION COMPLETED ON A SMITHS MEDICAL FLUID WARMING/LEVEL 1 HOTLINE LOW FLOW SYSTEMS - HL-90 COMPLAINT OF TEMPERATURE FLUCTUATIONS WAS VERIFIED DURING TESTING. THIS WAS ISOLATED TO A FAULTY PCB (PRIMARY CIRCUIT BOARD). THE DEVICE WAS FOUND TO HAVE WEAR AND TEAR UPON ARRIVAL FOR INVESTIGATION. FRONT COVER, TANK AND LINE CORD. OUTDATED PCB AND POWER SWITCH. NO ACTION WAS TAKEN TO REPAIR DEVICE AS DEEMED BEYOND REPAIR AND WILL BE SCRAPPED. NO CAUSE OF EVENT WAS ESTABLISHED.",
    )
    eq_(
        mdrtext[1]["text"],
        "INFORMATION RECEIVED A FLUID WARMING/LEVEL 1 HOTLINE LOW FLOW SYSTEMS - HL-90 TEMPERATURE WAS BOUNCING AROUND AND SHOWING AT 45 DEGREES CELSIUS BUT WAS AT 20 DEGREES CELSIUS. NO PATIENT ADVERSE EVENTS REPORTED.",
    )
